# Language description
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
cache: pip

# Command to install dependencies
install:
  - pip install -r requirements.txt

# Commands to run tests
script:
  - python3 -m unittest
